## Import Library

In [31]:
import numpy as np

## Problem 1: Array Creation

### 1. Initialize an empty array with size 2×2

In [32]:
arr1 = np.empty((2,2))
print(arr1)

[[2.5e-323 1.5e-323]
 [9.9e-324 4.9e-324]]


### 2. Initialize an all‑ones array with size 4×2

In [33]:
arr2 = np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### 3. Create an array filled with a specific value

In [34]:
arr3 = np.full((3,3),7)
print(arr3)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


### 4. Create zeros array with same shape as another array

In [35]:
base = np.array([[1,2,3],[4,5,6]])
zeros_like = np.zeros_like(base)
print(zeros_like)

[[0 0 0]
 [0 0 0]]


### 5. Create ones array with same shape as another array

In [36]:
ones_like = np.ones_like(base)
print(ones_like)

[[1 1 1]
 [1 1 1]]


### 6. Convert a list to NumPy array

In [37]:
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


## Problem 2: Array Manipulation

### 1. Create array with values from 10 to 49

In [38]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 2. Create a 3×3 matrix with values 0–8

In [39]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 3. Create a 3×3 identity matrix

In [40]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 4. Random array of size 30 and find mean

In [41]:
arr = np.random.random(30)
print(arr)
print('Mean:', arr.mean())

[0.72706318 0.72906582 0.88660788 0.50961313 0.08805055 0.85513734
 0.77966292 0.58430228 0.80881066 0.6510045  0.02706198 0.83838113
 0.61603841 0.9403116  0.30054966 0.91650146 0.15120762 0.38833357
 0.23771178 0.0226524  0.9594318  0.73635119 0.55306097 0.01461988
 0.31198019 0.25958313 0.08105173 0.7568367  0.37213639 0.29435682]
Mean: 0.513249222984157


### 5. 10×10 random array and find min and max

In [42]:
arr = np.random.random((10,10))
print('Min:', arr.min())
print('Max:', arr.max())

Min: 0.02115916546696317
Max: 0.9920561601361513


### 6. Zero array of size 10 and replace 5th element with 1

In [43]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Reverse the array

In [44]:
arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

[0 4 0 0 2 1]


### 8. Create 2D array with border = 1 and inside = 0

In [45]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 9. Create an 8×8 checkerboard pattern

In [46]:
board = np.zeros((8,8), dtype=int)
board[1::2, ::2] = 1
board[::2, 1::2] = 1
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Problem 3: Array Operations

In [47]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

### 1. Add arrays

In [48]:
print(x + y)

[[ 6  8]
 [10 13]]


### 2. Subtract arrays

In [49]:
print(x - y)

[[-4 -4]
 [-4 -3]]


### 3. Multiply array by integer

In [50]:
print(x * 3)

[[ 3  6]
 [ 9 15]]


### 4. Square each element

In [51]:
print(x ** 2)

[[ 1  4]
 [ 9 25]]


### 5. Dot products

In [52]:
print('v·w =', np.dot(v,w))
print('x·v =', np.dot(x,v))
print('x·y =')
print(np.dot(x,y))

v·w = 219
x·v = [29 77]
x·y =
[[19 22]
 [50 58]]


### 6. Concatenate arrays

In [53]:
print('Row concatenation:')
print(np.concatenate((x,y), axis=0))

print('\nColumn concatenation:')
print(np.column_stack((v,w)))

Row concatenation:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Column concatenation:
[[ 9 11]
 [10 12]]


### 7. Attempt to concatenate x and v (dimension mismatch)

In [54]:
# This will raise an error because x is 2D and v is 1D
# np.concatenate((x,v))

## Problem 4: Matrix Operations

In [55]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

### 1. Prove A · A⁻¹ = I

In [56]:
A_inv = np.linalg.inv(A)
print(np.dot(A, A_inv))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


### 2. Show AB ≠ BA

In [57]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print('AB =')
print(AB)

print('\nBA =')
print(BA)

AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]


### 3. Prove (AB)ᵀ = BᵀAᵀ

In [58]:
left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))

print(left)
print(right)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


## Solve Linear System Using NumPy

---



Equations:

2x − 3y + z = −1  
x − y + 2z = −3  
3x + y − z = 9

In [59]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

### Solve using NumPy linear solver

In [60]:
solution = np.linalg.solve(A,B)
print('Solution [x,y,z]:', solution)

Solution [x,y,z]: [ 2.  1. -2.]
